// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Pool {
    #[prost(string, tag="1")]
    pub pool_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub token_a_mint: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub token_b_mint: ::prost::alloc::string::String,
    #[prost(uint32, tag="4")]
    pub fee_tier_bps: u32,
    #[prost(double, tag="5")]
    pub volume_24h: f64,
    #[prost(double, tag="6")]
    pub fees_24h: f64,
    #[prost(double, tag="7")]
    pub apr_24h: f64,
    #[prost(double, tag="8")]
    pub tvl_estimate: f64,
    #[prost(double, tag="9")]
    pub token_a_balance: f64,
    #[prost(double, tag="10")]
    pub token_b_balance: f64,
    #[prost(string, tag="11")]
    pub token_a_symbol: ::prost::alloc::string::String,
    #[prost(string, tag="12")]
    pub token_b_symbol: ::prost::alloc::string::String,
    #[prost(uint32, tag="13")]
    pub token_a_decimals: u32,
    #[prost(uint32, tag="14")]
    pub token_b_decimals: u32,
    #[prost(double, tag="15")]
    pub tvl_usd: f64,
    #[prost(double, tag="16")]
    pub token_a_price_usd: f64,
    #[prost(double, tag="17")]
    pub token_b_price_usd: f64,
    #[prost(double, tag="18")]
    pub volume_24h_usd: f64,
    #[prost(double, tag="19")]
    pub fees_24h_usd: f64,
    #[prost(double, tag="20")]
    pub apr_24h_usd: f64,
    #[prost(double, tag="21")]
    pub volume_a_delta: f64,
    #[prost(double, tag="22")]
    pub volume_b_delta: f64,
    #[prost(double, tag="23")]
    pub fees_a_delta: f64,
    #[prost(double, tag="24")]
    pub fees_b_delta: f64,
    #[prost(double, tag="25")]
    pub lp_supply: f64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Position {
    #[prost(string, tag="1")]
    pub position_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub pool_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub token_a_mint: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub token_b_mint: ::prost::alloc::string::String,
    #[prost(uint32, tag="5")]
    pub fee_tier_bps: u32,
    #[prost(double, tag="6")]
    pub pool_value: f64,
    #[prost(string, tag="7")]
    pub token_a_symbol: ::prost::alloc::string::String,
    #[prost(string, tag="8")]
    pub token_b_symbol: ::prost::alloc::string::String,
    #[prost(uint32, tag="9")]
    pub token_a_decimals: u32,
    #[prost(uint32, tag="10")]
    pub token_b_decimals: u32,
    #[prost(double, tag="11")]
    pub token_a_balance: f64,
    #[prost(double, tag="12")]
    pub token_b_balance: f64,
    #[prost(double, tag="13")]
    pub pending_rewards: f64,
    #[prost(string, tag="14")]
    pub owner: ::prost::alloc::string::String,
    #[prost(double, tag="15")]
    pub lp_balance: f64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PoolHour {
    #[prost(string, tag="1")]
    pub pool_id: ::prost::alloc::string::String,
    #[prost(int64, tag="2")]
    pub hour: i64,
    #[prost(double, tag="3")]
    pub volume_a: f64,
    #[prost(double, tag="4")]
    pub volume_b: f64,
    #[prost(double, tag="5")]
    pub fees_a: f64,
    #[prost(double, tag="6")]
    pub fees_b: f64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MyData {
    #[prost(uint64, tag="1")]
    pub slot: u64,
    #[prost(int64, tag="2")]
    pub timestamp: i64,
    #[prost(message, repeated, tag="3")]
    pub pools: ::prost::alloc::vec::Vec<Pool>,
    #[prost(message, repeated, tag="4")]
    pub positions: ::prost::alloc::vec::Vec<Position>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HourlyData {
    #[prost(uint64, tag="1")]
    pub slot: u64,
    #[prost(int64, tag="2")]
    pub timestamp: i64,
    #[prost(message, repeated, tag="3")]
    pub pool_hours: ::prost::alloc::vec::Vec<PoolHour>,
}
// @@protoc_insertion_point(module)
